import OpenAI from "openai";
import { sha256 } from "@/lib/utils";
import type { UrgencyLevel, ConditionScore } from "@/lib/inference/types";

export interface SummaryInput {
  sessionId: string;
  urgencyLevel: UrgencyLevel;
  urgencyReason: string;
  redFlags: string[];
  conditionGroups: ConditionScore[];
  intake: Record<string, unknown>;
  engineVersion: string;
  captureDate: string;
}

const SYSTEM_PROMPT = `You are a clinical documentation assistant generating a physician-facing triage note from structured data.

Rules:
- Use clinical language appropriate for a GP or specialist referral letter
- Frame findings as "suggests possible", "consistent with", "warrants evaluation for" — never as diagnoses
- Be concise: 1–3 sentences per section
- Always include the disclaimer section exactly as specified
- Do not add information not present in the input data
- Output plain text with section headers in ALL CAPS followed by a colon`;

function buildUserPrompt(input: SummaryInput): string {
  const groups = input.conditionGroups
    .map(
      (g) =>
        `  - ${g.label} (${g.confidence} confidence${g.showPercentage ? `, ${g.matchScore}% pattern match` : ""}): ${(g.featuresMatched ?? []).join(", ") || "visual pattern match"}`
    )
    .join("\n");

  const intake = input.intake as Record<string, unknown>;

  return `Generate a triage summary note with exactly these sections:

PRESENTING CONCERN: Summarise chief complaint, onset, and duration from intake data.
OBSERVED FEATURES: List the visual and motion findings from matched condition groups as bullet points.
SYMPTOM HISTORY: Structured summary of the patient's reported symptoms.
DIFFERENTIAL CONSIDERATIONS: List condition groups with confidence labels. Never present as diagnoses.
URGENCY ASSESSMENT: State the urgency level with clinical reasoning.
RECOMMENDED NEXT STEPS: Consolidated, prioritised action items for the treating clinician.
DISCLAIMER: "This triage summary was generated by an AI-assisted pattern recognition tool and does not constitute a medical diagnosis. All findings require clinical verification by a qualified health professional. This report is intended to support, not replace, clinical judgement."

Input data:
${JSON.stringify(
  {
    capture_date: input.captureDate,
    engine_version: input.engineVersion,
    urgency_level: input.urgencyLevel,
    urgency_reason: input.urgencyReason,
    red_flags: input.redFlags,
    condition_groups: groups,
    intake_summary: {
      chief_complaint: intake.chief_complaint,
      age: intake.age,
      sex: intake.sex,
      onset_days: intake.onset_days,
      is_sudden: intake.is_sudden,
      pain_level: intake.pain_level,
      has_facial_drooping: intake.has_facial_drooping,
      vision_changes: intake.vision_changes,
      has_headache: intake.has_headache,
      has_numbness: intake.has_numbness,
      breathing_difficulty: intake.breathing_difficulty,
      has_rash: intake.has_rash,
      has_swelling: intake.has_swelling,
      has_fever: intake.has_fever,
      recent_illness: intake.recent_illness,
      medical_history: intake.medical_history,
    },
  },
  null,
  2
)}`;
}

export async function generateDoctorSummary(
  input: SummaryInput
): Promise<{ summaryText: string; modelUsed: string; promptHash: string }> {
  const client = new OpenAI({
    apiKey: process.env.DEEPSEEK_API_KEY,
    baseURL: "https://api.deepseek.com",
  });

  const model = process.env.DEEPSEEK_MODEL ?? "deepseek-chat";
  const userPrompt = buildUserPrompt(input);
  const promptHash = await sha256(userPrompt);

  const response = await client.chat.completions.create({
    model,
    max_tokens: 1200,
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user", content: userPrompt },
    ],
  });

  const summaryText = response.choices[0]?.message?.content ?? "";

  return { summaryText, modelUsed: model, promptHash };
}
