"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useSession } from "@/components/shared/SessionContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Printer, AlertTriangle, ArrowLeft } from "lucide-react";
import { formatDate, formatTime } from "@/lib/utils";

export default function SummaryPage() {
  const router = useRouter();
  const { sessionId } = useSession();
  const [summaryText, setSummaryText] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [generatedAt] = useState(new Date());

  useEffect(() => {
    if (!sessionId) { router.push("/consent"); return; }

    fetch("/api/summary", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ sessionId }),
    })
      .then(async (res) => {
        if (!res.ok) throw new Error("Failed to generate summary");
        return res.json();
      })
      .then((data) => setSummaryText(data.summaryText))
      .catch(() => setError("Could not generate summary. Please try again."))
      .finally(() => setLoading(false));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId]);

  function formatSummary(text: string) {
    const lines = text.split("\n");
    return lines.map((line, i) => {
      if (line.match(/^[A-Z\s]+:/)) {
        return (
          <div key={i} className={i > 0 ? "mt-5" : ""}>
            <h3 className="font-bold text-sm uppercase tracking-wide text-gray-700 border-b pb-1 mb-2">
              {line}
            </h3>
          </div>
        );
      }
      if (line.startsWith("  - ") || line.startsWith("- ")) {
        return (
          <li key={i} className="text-sm text-gray-800 ml-4 list-disc">
            {line.replace(/^\s*-\s*/, "")}
          </li>
        );
      }
      if (line.trim() === "") return <br key={i} />;
      return (
        <p key={i} className="text-sm text-gray-800">
          {line}
        </p>
      );
    });
  }

  if (loading) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center gap-4 px-4">
        <div className="w-8 h-8 rounded-full border-4 border-blue-200 border-t-blue-600 animate-spin" />
        <p className="text-sm text-muted-foreground">Generating doctor summary…</p>
      </div>
    );
  }

  if (error || !summaryText) {
    return (
      <div className="min-h-screen flex items-center justify-center px-4">
        <div className="text-center space-y-4">
          <AlertTriangle className="h-10 w-10 text-amber-500 mx-auto" />
          <p className="text-muted-foreground">{error ?? "Summary unavailable."}</p>
          <Button onClick={() => router.push("/results")}>Back to results</Button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-2xl mx-auto px-4 py-8 space-y-5">
        {/* Header */}
        <div className="no-print">
          <button
            onClick={() => router.push("/results")}
            className="flex items-center gap-1 text-sm text-muted-foreground mb-4 hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" /> Back to results
          </button>
        </div>

        <div className="print-header">
          <h1 className="text-2xl font-bold">Doctor Triage Summary</h1>
          <p className="text-sm text-muted-foreground">
            Generated {formatDate(generatedAt)} at {formatTime(generatedAt)} &middot; Facial Triage Assistant v1.0
          </p>
        </div>

        {/* Summary body */}
        <Card>
          <CardContent className="pt-6 pb-6">
            <div className="space-y-1">{formatSummary(summaryText)}</div>
          </CardContent>
        </Card>

        {/* Non-diagnostic notice */}
        <Card className="border-amber-200 bg-amber-50">
          <CardContent className="pt-4 pb-4">
            <p className="text-xs text-amber-800">
              <strong>Important:</strong> This summary was generated by an AI-assisted pattern recognition
              tool and does not constitute medical advice or a clinical diagnosis. It is intended to
              support, not replace, the judgement of a qualified health professional.
            </p>
          </CardContent>
        </Card>

        {/* Actions */}
        <div className="flex gap-3 no-print">
          <Button
            variant="outline"
            className="flex-1 gap-2"
            onClick={() => window.print()}
          >
            <Printer className="h-4 w-4" /> Print summary
          </Button>
          <Button
            className="flex-1"
            onClick={() => router.push("/")}
          >
            Start new assessment
          </Button>
        </div>

        <p className="text-xs text-muted-foreground text-center no-print">
          Take this summary to your GP or specialist appointment for follow-up.
        </p>
      </div>
    </div>
  );
}
