"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useSession } from "@/components/shared/SessionContext";
import { Printer, ArrowLeft } from "lucide-react";
import { formatDate, formatTime } from "@/lib/utils";

export default function SummaryPage() {
  const router = useRouter();
  const { sessionId } = useSession();
  const [summaryText, setSummaryText] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [generatedAt] = useState(new Date());

  useEffect(() => {
    if (!sessionId) { router.push("/consent"); return; }
    fetch("/api/summary", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ sessionId }),
    })
      .then(async (res) => {
        const data = await res.json();
        if (!res.ok) throw new Error(data.error ?? "Failed to generate summary");
        return data;
      })
      .then((data) => setSummaryText(data.summaryText))
      .catch((err: Error) => setError(err.message))
      .finally(() => setLoading(false));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId]);

  function formatSummary(text: string) {
    return text.split("\n").map((line, i) => {
      if (line.match(/^[A-Z\s]+:/)) {
        return (
          <div key={i} className={i > 0 ? "mt-6" : ""}>
            <p className="text-[10px] font-semibold tracking-[0.2em] uppercase text-gray-400 border-b border-gray-100 pb-1.5 mb-2">
              {line}
            </p>
          </div>
        );
      }
      if (line.startsWith("  - ") || line.startsWith("- ")) {
        return (
          <li key={i} className="text-sm text-gray-600 ml-4 list-disc leading-relaxed">
            {line.replace(/^\s*-\s*/, "")}
          </li>
        );
      }
      if (line.trim() === "") return <br key={i} />;
      return <p key={i} className="text-sm text-gray-600 leading-relaxed">{line}</p>;
    });
  }

  if (loading) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center gap-5 px-4" style={{ background: "#fafaf9" }}>
        <div className="w-8 h-8 rounded-full border border-gray-200 border-t-gray-900 animate-spin" />
        <p className="text-sm text-gray-400">Generating doctor summary…</p>
      </div>
    );
  }

  if (error || !summaryText) {
    return (
      <div className="min-h-screen flex items-center justify-center px-4" style={{ background: "#fafaf9" }}>
        <div className="text-center space-y-4">
          <p className="text-gray-400 text-sm">{error ?? "Summary unavailable."}</p>
          <button
            onClick={() => router.push("/results")}
            className="rounded-full border border-gray-200 px-6 py-2.5 text-sm text-gray-500 hover:border-gray-400 transition-colors"
          >
            Back to results
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen" style={{ background: "#fafaf9" }}>
      <div className="max-w-2xl mx-auto px-5 py-10 space-y-6">
        <div className="no-print">
          <button
            onClick={() => router.push("/results")}
            className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-gray-600 mb-6 transition-colors"
          >
            <ArrowLeft className="h-3.5 w-3.5" /> Back to results
          </button>
        </div>

        <div className="print-header">
          <p className="text-[10px] font-semibold tracking-[0.25em] uppercase text-gray-400 mb-2">Doctor summary</p>
          <h1 className="text-2xl font-light text-gray-900">Triage note</h1>
          <p className="text-xs text-gray-400 mt-1">
            {formatDate(generatedAt)} at {formatTime(generatedAt)} · Facial Triage Assistant v1.0
          </p>
        </div>

        <div className="bg-white border border-gray-100 rounded-xl p-6">
          <div className="space-y-1">{formatSummary(summaryText)}</div>
        </div>

        <div className="border border-gray-100 rounded-xl p-4">
          <p className="text-xs text-gray-400 leading-relaxed">
            <strong className="font-medium text-gray-500">Important:</strong> This summary was generated by an AI-assisted pattern recognition
            tool and does not constitute medical advice or a clinical diagnosis. It is intended to
            support, not replace, the judgement of a qualified health professional.
          </p>
        </div>

        <div className="flex gap-3 no-print">
          <button
            onClick={() => window.print()}
            className="flex-1 flex items-center justify-center gap-2 rounded-full border border-gray-200 py-3 text-sm text-gray-600 hover:border-gray-400 transition-colors"
          >
            <Printer className="h-4 w-4" /> Print
          </button>
          <button
            onClick={() => router.push("/")}
            className="flex-1 rounded-full bg-gray-900 py-3 text-sm text-white hover:bg-gray-700 transition-colors"
          >
            New assessment
          </button>
        </div>

        <p className="text-xs text-gray-400 text-center no-print">
          Take this note to your GP or specialist appointment.
        </p>
      </div>
    </div>
  );
}
